# Generated by Django 5.2.17 on 2026-08-14 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('accident_date', models.DateField()),
                ('accident_image', models.ImageField(upload_to='accident_images/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotated_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='claims.claimrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DamageDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('yolo_confidence', models.FloatField()),
                ('severity', models.CharField(choices=[('no_damage', 'No Damage'), ('minor', 'Minor Damage'), ('moderate', 'Moderate Damage'), ('major', 'Major Damage')], max_length=10)),
                ('severity_confidence', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='claims.claimrequest')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'unique_together': {('brand', 'manufacturing_year')},
            },
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='vehicle_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.vehicledetails'),
        ),
    ]
